
format:
  html:
    theme: [default, ../resources/tut-style.scss]
    css: ../resources/tut-style.css
    toc: true
    toc-float: true
    page-layout: full
    ## Code
    code-fold: false
    code-tools: true
    code-summary: "Show the code"
    code-line-numbers: true
    code-block-border-left: "#ccc"
    code-copy: true
    highlight-style: atom-one
    number-sections: true
    number-depth: 3
    embed-resources: true

execute:
  freeze: auto