---
title: SUYR Statistics resources 
author: "Murray Logan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
crossref:
  fig-title: '**Figure**'
  fig-labels: arabic
  tbl-title: '**Table**'
  tbl-labels: arabic
engine: knitr
bibliography: ../resources/references.bib
output_dir: "docs"
---

## Tutorials

- [Tutorial instructions](001_instructions.html)
- [Setup instructions](005_setup.html)

### R basics

- [Introduction to R](01_introduction_to_r.html)
- [Editors](02_editors.html)
- [Data frames](03_data_frames.html)
- [Data wrangling](04_data_wrangling.html)
- [Grammar of graphics](05_grammar_of_graphics.html)
 
### Reproducible research

- [Git and version control](10_git.html)
- [Containerisation - docker and singularity](12_docker.html)

### Statistical principles

- [Basic statistical principles](20_basic_principles.html)
- [Statistical philosophies](21_statistical_philosophies.html)
- [Estimation](22_estimation.html)
- [Causal inference](25_causation.html)

### Introduction to linear modelling

- [Generalised linear models](30_glm.html)
- [Bayesian generalised linear models](35_bayesian_glm.html)

## Presentations

- [Course introduction](01_introduction.html)
- [git and github](10_pres_git.html)
- [Introduction to Bayesian analyses](20_pres_bayesian.html)
- [Introduction to hierarchical models](30_pres_hierarchical.html)
- [Introduction to Generalised Additive Models](40_pres_gams.html)
- [Introduction to regression trees](50_pres_trees.html)
- [Introduction to multivariate analyses](60_pres_multivariate.html)
 
