
name: Render and Publish Tutorials

on:
  workflow_dispatch:
#  push:
#    branches: ['main']

env:
  IMAGE_NAME: pcinereus/suyrs_documents

jobs:
  render-tutorials:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0  # Ensure git history is available

      - name: Get last GitHub Pages deployment timestamp
        run: |
          DEPLOY_TIME_RAW=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pages/builds" | jq -r '.[0].updated_at')
          DEPLOY_TIME=$(date -d "$DEPLOY_TIME_RAW" +%s)
          echo "Last deployment: $DEPLOY_TIME_RAW ($DEPLOY_TIME)"
          echo "DEPLOY_TIME=$DEPLOY_TIME" >> $GITHUB_ENV

      - name: Find modified .qmd files
        run: |
          git ls-tree -r --name-only origin/main | grep '\.qmd$' | while read file; do
          #MODIFIED_TIME=$(git log -1 --format="%ci" -- "$file")
            MODIFIED_TIME_RAW=$(git log -1 --format="%ci" -- "$file")
            MODIFIED_TIME=$(date -d "$MODIFIED_TIME_RAW" +%s)
          #echo "$MODIFIED_TIME"
            echo "File: $file | Modified: $MODIFIED_TIME_RAW ($MODIFIED_TIME)"
            if [[ "$MODIFIED_TIME" > "$DEPLOY_TIME" ]]; then
              echo "$file was modified after last deployment."
              echo "$file" >> changed_files.txt
            fi
          done

          echo "Changed files:"
          cat changed_files.txt || echo "No changes found."
    
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Docker Image
        run: docker pull ghcr.io/${{ env.IMAGE_NAME }}:latest

      #- name: Run Container and Render Updated Files
      #  run: |
      #    docker run --rm -v $PWD:/workspace -w /workspace ghcr.io/${{ env.IMAGE_NAME }}:latest \
      #    bash -c "cp gh-pages-folder/*.html tut/ && make tut"
      #    #bash -c "cp gh-pages-folder/*.html tut/ && ls -la tut"
      #    #bash -c "git diff --name-only HEAD~1 HEAD | grep '\.qmd$' | xargs -I {} quarto render {}"
      - name: Render Updated Quarto Files
        run: |
          mkdir ~/tmp
          if [ -s changed_files.txt ]; then
            docker run --privileged --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/workspace -w /workspace ghcr.io/${{ env.IMAGE_NAME }}:latest \
            bash -c "cat changed_files.txt | xargs -I {} quarto render {}"
          else
            echo "No updated files to render."
          fi
          ls -lat
          ls -lat tut
          mkdir docs
          cp tut/*.html docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
