name: Test rendering via nix

on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches: ['release']

jobs:
  render-tutorials:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          log-directives: nix_installer=trace
          backtrace: full

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build development environment
        run: |
          nix-build
          - name: Make tutorials
          
      - name: Test    
        run: |
          echo "library(brms); dat <- data.frame(y = rnorm(10), x = rnorm(10)); brm(y ~ x, data = dat, backend = "cmdstanr");" | R --no-save --no-restore;
