name: Test imagemagick

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libjpeg-dev libpng-dev libtiff-dev libgif-dev
          wget https://download.imagemagick.org/ImageMagick/download/ImageMagick.tar.gz
          tar xvzf ImageMagick.tar.gz
          cd ImageMagick-*
          ./configure
          make
          sudo make install
          sudo ldconfig /usr/local/lib

      - name: Verify ImageMagick installation
        run: |
          magick --version
          which magick

      - name: Test magick command
        run: |
          magick -size 100x100 xc:white test.png

